services:
  - type: web
    name: novarsis-chatbot
    runtime: docker
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: OLLAMA_API_KEY
        sync: false
      - key: OLLAMA_BASE_URL
        value: https://ollama.com
      - key: OLLAMA_MODEL
        value: qwen3-coder:480b